/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pearlsofpune;

/**
 *
 * @author mohit
 */
public class info extends javax.swing.JFrame {

    /**
     * Creates new form info
     */
    public info() {
        initComponents();
        hotels.setLineWrap(true);
        entertainment.setLineWrap(true);
        hospitals.setLineWrap(true);
        transport.setLineWrap(true);
        tourist_attraction.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        hotels = new javax.swing.JTextArea();
        hotels_5star = new javax.swing.JButton();
        hotels_4star = new javax.swing.JButton();
        hotels_3star = new javax.swing.JButton();
        hotels_others = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        entertainment = new javax.swing.JTextArea();
        ent_malls = new javax.swing.JButton();
        ent_beaches = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hospitals = new javax.swing.JTextArea();
        hosp_private = new javax.swing.JButton();
        hosp_govt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        transport = new javax.swing.JTextArea();
        trans_road = new javax.swing.JButton();
        trans_rail = new javax.swing.JButton();
        trans_air = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tourist_attraction = new javax.swing.JTextArea();
        tourist_relig = new javax.swing.JButton();
        tourist_hist = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(207, 72, 72));
        setMaximumSize(new java.awt.Dimension(570, 440));
        setMinimumSize(new java.awt.Dimension(570, 440));
        setPreferredSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pearls of Pune");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 140, 25));

        hotels.setColumns(20);
        hotels.setRows(5);
        jScrollPane14.setViewportView(hotels);

        hotels_5star.setText("5 star");
        hotels_5star.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotels_5starActionPerformed(evt);
            }
        });

        hotels_4star.setText("4 star");
        hotels_4star.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotels_4starActionPerformed(evt);
            }
        });

        hotels_3star.setText("3 star");
        hotels_3star.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotels_3starActionPerformed(evt);
            }
        });

        hotels_others.setText("Others");
        hotels_others.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotels_othersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hotels_5star)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hotels_4star)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hotels_3star)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hotels_others)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotels_5star)
                    .addComponent(hotels_4star)
                    .addComponent(hotels_3star)
                    .addComponent(hotels_others))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hotels", jPanel1);

        entertainment.setColumns(20);
        entertainment.setRows(5);
        jScrollPane1.setViewportView(entertainment);

        ent_malls.setText("Malls");
        ent_malls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ent_mallsActionPerformed(evt);
            }
        });

        ent_beaches.setText("Beaches");
        ent_beaches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ent_beachesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ent_malls)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ent_beaches)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ent_malls)
                    .addComponent(ent_beaches))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Entertainment", jPanel2);

        hospitals.setColumns(20);
        hospitals.setRows(5);
        jScrollPane2.setViewportView(hospitals);

        hosp_private.setText("Private");
        hosp_private.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosp_privateActionPerformed(evt);
            }
        });

        hosp_govt.setText("Government");
        hosp_govt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosp_govtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hosp_private)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hosp_govt)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hosp_private)
                    .addComponent(hosp_govt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jTabbedPane1.addTab("Hospitals", jPanel3);

        transport.setColumns(20);
        transport.setRows(5);
        jScrollPane3.setViewportView(transport);

        trans_road.setText("Rail");
        trans_road.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trans_roadActionPerformed(evt);
            }
        });

        trans_rail.setText("Road");
        trans_rail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trans_railActionPerformed(evt);
            }
        });

        trans_air.setText("Air");
        trans_air.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trans_airActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(trans_road)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trans_rail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trans_air)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trans_road)
                    .addComponent(trans_rail)
                    .addComponent(trans_air))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jTabbedPane1.addTab("Transport", jPanel4);

        tourist_attraction.setColumns(20);
        tourist_attraction.setRows(5);
        jScrollPane4.setViewportView(tourist_attraction);

        tourist_relig.setText("Religious");
        tourist_relig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tourist_religActionPerformed(evt);
            }
        });

        tourist_hist.setText("Historical");
        tourist_hist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tourist_histActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tourist_relig)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tourist_hist)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tourist_relig)
                    .addComponent(tourist_hist))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tourist Attraction", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 540, 330));

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void hotels_5starActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotels_5starActionPerformed
        // TODO add your handling code here:
        hotels.setText("The Pride Hotel\n5 University Road, Shivaji Nagar\nPhone: 02024657985\n\n"+
                "The Corinthians Resort & Club\nNyati County, NIBM Annexxe South Pune\nPhone: 02024657246\n\n"+
                "Sun N Sand Hotel\n262,Bund Garden Road\nPhone: 02024624546\n\n"+
                "Oakwood Residence\n1 C Naylor Road, Off Managaldas Road\nPhone: 02024624246\n\n");
    }//GEN-LAST:event_hotels_5starActionPerformed

    private void hotels_4starActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotels_4starActionPerformed
        // TODO add your handling code here:
        hotels.setText("Hyatt Pune\n88 Adjacent To Aga Khan Palace Nagar Road\nPhone:02041411234\n\n"+
                "Radisson Blu Hotel\nNagar Bypass Road | Kharadi\nPhone:02041258234\n\n"+
                "Four Points By Sheraton\n5th Milestone, Pune\nPhone:02041274594\n\n"+
                "Royal Orchid Central\nKalyani Nagar Marisoft Annexe | Marisoft Annexe\nPhone:02045121254\n\n");
    }//GEN-LAST:event_hotels_4starActionPerformed

    private void hotels_3starActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotels_3starActionPerformed
        // TODO add your handling code here:
        hotels.setText("Vivanta by Taj - Blue Diamond\n11 Koregaon Road\nPhone: 020 6602 5555\n\n"+
                "Premier Inn Pune Kharadi Hotel\nPune Kharadi, Kharadi Mundhawa | Bypass Road, Next to Dominos\nPhone: 020 6602 2755\n\n"+
                "Royal Orchid Golden Suites\nOpp Cerebrum It Park | Kalyani Nagar\nPhone: 020 2402 5375\n\n");
    }//GEN-LAST:event_hotels_3starActionPerformed

    private void hotels_othersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotels_othersActionPerformed
        // TODO add your handling code here:
        hotels.setText("Maitri Lodge\nflat no 106, G block M.I.D.C, near gati godawa, thermax chowk chinchwad\nPhone: 020 4205 0514\n\n"+
                "Hotel Sheetal\n1180, Shivajinagar,Dnyaneshwar Paduka Chowk, F.C Road Pune\nPhone: 020 4220 1124\n\n"+
                "Hotel Om Sai Palace\n1202/34, Shirole Road, Off Apte Road, Shivajinagar\nPhone: 020 4057 5542\n\n"+
                "Hotel Bhooshan\n1170/7, Shivajinagar, Revenue Colony, Behind Jangli Maharaj Temple, Adj. Lane of Surbhi\nPhone: 020 4521 1245\n\n");
    }//GEN-LAST:event_hotels_othersActionPerformed

    private void hosp_privateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosp_privateActionPerformed
        // TODO add your handling code here:
        hospitals.setText("Ruby Hall Clinic\nRuby Hall Clinic 40, Sassoon Road\nPhone: 020 - 26163391\nEmail: info@rubyhall.com\n\n"+
                "Jehangir Hospital\n32, Sassoon Road\nPhone: 66819999, 66811000\nE-mail: enquiry@jehangirhospital.com\n\n"+
                "Deenanath Mangeshkar Hospital and Research Centre\nErandawne, Pune 411 004\nPhone: +91 20 40151000 / 66023000\nEmail : info@dmhospital.org /jpmt@vsnl.com\n\n"+
                "KEM Hospital\nSardar Moodliar Road\nPhone: 26125224, 66037300, 66037408\nE-mail: marketing@kemhospital.org\n\n"+
                "Sancheti Institute For Orthopaedics & Rehabilitation\n16, Shivaji Nagar, Pune\nPhone: (020) 28 999 999, 27 999 999 \nEmail: sanchetihospital@eth.net, parag@sanchetihospital.org\n\n");
    }//GEN-LAST:event_hosp_privateActionPerformed

    private void hosp_govtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosp_govtActionPerformed
        // TODO add your handling code here:
        hospitals.setText("Janaki Nursing Home\nKarve Nagar, Kothrud\nPhone:020 - 25440386\n\n"+
                "Lifeline Hospital, Ganeshkhind\n#157, Legacy, D.P. Road, Ganeshkhind\nPhone: 020 - 25882053\n\n"+
                "Madhuban Hospitals Private Limited\n#365, Donje, Parvati\nPhone: 020 - 24389647\n\n"+
                "Military Hospital, N.D.A.\nNDA Khadakwasla, N.D.A., Pune\nPhone: 020 - 25293200\n\n"+
                "Neo Clinic, Model Colony\n#917/2, Mayur Center, Fergusson College Road, Model Colony\nPhone: 020 - 25661679\n\n"+
                "King Edward Memorial Hospital\nRasta Sardar Mudliar Road, Kasba Peth\nPhone: 020 - 26141177\n\n");
    }//GEN-LAST:event_hosp_govtActionPerformed

    private void ent_mallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ent_mallsActionPerformed
        // TODO add your handling code here:
        entertainment.setText("Phoenix Market City\nNagar Road, Pune 411030\nPhone Number: +91 20 3095 0000\nReviews:\n> All the big names are there. Clean and well kept and good service.courteous staff and helpful. Prices could be over the average but makes for good taste.\n> One of the biggest malls in Pune , is definitely crowded , good food options with different variety , coffee shops and high end stores. Awesome !\n\n"+
                "Seasons Mall\nSolapur Highway, Pune 411028\nPhone Number: +91 20 6722 4000\nReviews:\n> New mall opened near Hadapsar area.Just infront of Amanora Mall. Have almost all the leading Branded stores outlets.Have Star Bazaar for grocery shopping.Food courts are good.We have Cinepolis here for Movies.Good mall to visit with family and friends.\n> You must this place.I enjoy with my friend.Various facilities available for visitors....This place one of the best place in pune to visit...Mall closed @10.3pPm\n\n"+
                "Sgs Mall\n No 231 Aundh Camp Internal Road | Near Hdfc Bank, Pune 411002\nPhone Number: +91 20 2633 2865\nReviews:\n> It's a small mall .. It's nice but has limited brands and hence limits option .. They have awesome sale in this mall though.. Came across marks and spencer here.. With insane sale going on .. Made me super happy\n> SGS Mall is one of the oldest malls in Pune. The showrooms and outlets are very restricted with nothing great at offer. Unless you are in the area and dont want to travel to other parts of the city, you can easily skip this one. There are much better shopping destinations.\n\n");
    }//GEN-LAST:event_ent_mallsActionPerformed

    private void ent_beachesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ent_beachesActionPerformed
        // TODO add your handling code here:
        entertainment.setText("Tarkarli Beach\nDistance from Pune: 388 Kilometers (approx.)\nPopular for the mesmerising beauty it holds, Tarkarli Beach is known for the long and narrow stretch sea coast. It gives you one of the most relaxing experiences and can make your sunsets blissful. You are sure to rejuvenate in the calm and serene atmosphere of this highly placid beach destination, just a few miles away from Pune!\n\n"+
                "Alibag Beach\nDistance from Pune: 143 Kilometers (approx.)\nOne of the most popular weekend getaways from Pune, Alibag is a hub for Mubaikars and Pune dwellers. Not just the beach, you also have a number of things to visit and sightsee here. One of the famous tourist spots in Alibag is the Kulaba Fort which can be visited only in the gap between the high and low tide. Apart from this, the beautiful beach also has places like Magnetic Observatory, Kanhoji Angre Samadhi, Vikram Vinakyak temple and the tower of St. Barbara making it an amazing tourist destination near Pune.\n\n"+
                "Mandwa Beach\nDistance from Pune: 150 Kilometers (approx.)\nMandwa village has a charm of its own with its striking groves of coconut palms. Through this is your ride that will take you to the spell bounding Mandwa Beach! Relax, take a day off and head to this popular destination that has a number of sightseeing places ready in store for you.  On a clear day you can also enjoy a breath-taking view across the bay, up to the Gateway of India.\n\n"+
                "Ganpatipule Beach\nDistance from Pune: 316 Kilometers (approx.)\nBesides the calm and sedate Ganpatipule village, stretches this serene coastline beauty called the Ganpatipule Beach. Situated on the Konkan coast, this sea shore is a home for variety of cuisines and amazing landscape. It doesn’t take much to get there and is surely one of the best beaches in India; you are definite to leave this place with a relaxed and sober mind.\n\n");
    }//GEN-LAST:event_ent_beachesActionPerformed

    private void trans_airActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trans_airActionPerformed
        // TODO add your handling code here:
        transport.setText("Pune Airport is an international airport at Lohegaon, operated by the Airports Authority of India.\n It shares its runways with the neighbouring Indian Air Force base.[1] In addition to domestic flights to all major Indian cities, this airport serves international direct flights to Dubai (operated by Air India Express)[2] and to Frankfurt (operated by Lufthansa).[3]\n" +
"The Maharashtra Industrial Development Corporation is responsible for the design and construction of a New Pune International Airport. The area between Chakan and Rajgurunagar, around the villages of Chandus and Shiroli, is being considered as a construction site. If constructed here, it will be at a distance of 40 km (25 mi) from central Pune.[4]\n\n");
    }//GEN-LAST:event_trans_airActionPerformed

    private void trans_roadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trans_roadActionPerformed
        // TODO add your handling code here:
        transport.setText("Public buses within the city and its suburbs are operated by the Pune Mahanagar Parivahan Mahamandal Limited (PMPML). The PMPML operates the Pune Bus Rapid Transit system, the first of its kind in India, in which dedicated bus lanes were supposed to allow buses to travel quickly through the city. In reality the project has turned out to be a failure receiving little to no patronage from the local citizenry.[8] Maharashtra State Road Transport Corporation runs buses from its main stations in Shivajinagar, Pune station and Swargate to all major cities and towns in Maharashtra and neighbouring states. Private companies too run buses to major cities throughout India.[9]\n" +
"\n" +
"Pune is well-connected to other cities by Indian highways and state highways. National Highway 4 (NH 4) connects it to Mumbai, Bangalore and Kolhapur. NH 9 to Hyderabad, and NH 50 to Nashik. State highways connect it to Ahmednagar, Aurangabad, and Alandi.Car Rental Services in Pune Pride Taxi Services Radio Taxis\n" +
"The Mumbai-Pune Expressway, India's first six-lane high-speed expressway, was built in 2002, and has reduced travel time between Pune and Mumbai to almost two hours. A ring road is being planned for the convenience of heavy traffic.[10]\n" +
"Pune is served by two intra-city highways: Old Pune-Mumbai Highway and Katraj-Dehu Road Bypass, a part of National Highway 4. The Nashik City-Pune Highway NH 50 will be part of the golden triangle(Nashik-Pune-Mumbai).\n\n");
    }//GEN-LAST:event_trans_roadActionPerformed

    private void trans_railActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trans_railActionPerformed
        // TODO add your handling code here:
        transport.setText("Local trains (EMUs) connect Pune to the industrial town of Pimpri-Chinchwad and the hill station of Lonavala, while daily express trains connect Pune to Mumbai, Hyderabad, Delhi, Nagpur, Kanpur, Howrah, Jammu Tawi, Chennai, Bangalore, Goa, Varanasi, Patna, and Jamshedpur. At Pune, there is diesel locomotive shed and electric trip shed.[5] A rapid transit system has been proposed in Pune and is scheduled to begin operations in 2013.[6] Pune Metro Rail is being planned in consultation with Delhi Metro Rail Corporation Limited, the corporation which built and operates the Delhi Metro. It will be a combination of elevated and underground sections, with initial routes being planned between Pimpri-Swargate and Vanaz-Ramwadi.\n\n" +
"The city has a railway station, Pune Railway Station. The station is administrated by the Pune Railway Division of the Central Railways.[7] All the railway lines to Pune are broad gauge.\n\n");
        
    }//GEN-LAST:event_trans_railActionPerformed

    private void tourist_religActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tourist_religActionPerformed
        // TODO add your handling code here:
        tourist_attraction.setText("Omkareshwar Temple\nDedicated to Lord Shiva and Goddess Parvati, the Omkareshwar Temple is a famous Jyotirlinga in the Shaniwar Peth locality of Pune. It was built in the 17th century during the reign of Sadashivrao Bhau. The temple's location, on the banks of the Mutha River, makes it a tranquil place of worship. It is also used as a place for performing the last rites for Hindus. The Nagara style architecture of the Omkareshwar Temple is characterised by a beautifully carved dome in white soap stone and a tower or shikhara, with five layers depicting different deities. \n\n"+
                "Chaturshringi Temple\nThe Chaturshringi Temple is one of the most popular tourist attractions in Pune. Built during the reign of Chhatrapati Shivaji, the great Maratha ruler, the temple holds much prominence during the Navratri festival, when it is beautifully decorated and lit. It stands 90 feet high on a hill slope at the Senapati Bapat Road. The temple is dedicated to Goddess Chaturshringi or Ambareshwari and represents strength and devotion. The goddess' shrine is located at an elevation that devotees cover by climbing 100 steps. In addition to the shrine, the complex has a temple for Lord Ganesha, which has eight idols of Him, and Goddess Durga. \n\n"+
                "Pataleshwar Cave Temple\nReminding one of the elaborate Ellora Caves in the western coast of India, the Pataleshwar Cave Temple is a similar rock-cut temple on the Jungraj Maharaj Road in Pune. Carved out of a single huge block of rock, the temple is an eighth century architectural marvel. Its various structures and seating arrangements depict ancient architects' extensive geometric knowledge. It is no wonder that today the cave temple is a government-declared protected monument. The Pataleshwar Cave Temple is dedicated to Lord Shiva, and has sculptures depicting ancient gods and goddess. An interesting feature of this temple is its museum, which has some astounding Guinness World Record-winning arts displayed for the visitors\n\n"+
                "Ganapati Temple\nLord Ganapati or Ganesha is a very popular diety in Maharashtra. It is no wonder, then, that the Shreemant Dagdusheth Halwai Ganapati Temple in Pune is a renowned religious site. The festival commemorating Ganesh Chaturthi is celebrated with much pomp and show here, with the involvement of the state's leaders and celebrities. Built in the 17th century, this temple on the banks of the Krishna River is considered an architectural wonder. It boasts of a large statue of Lord Ganesha in black stone and an ornate door made of natural wood, which interestingly is multi-coloured. The temple is also associated with various myths and legends.\n\n");
    }//GEN-LAST:event_tourist_religActionPerformed

    private void tourist_histActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tourist_histActionPerformed
        // TODO add your handling code here:
        tourist_attraction.setText("Darshan Museum\nSadhu Vaswani Mission, 10 Sadhu Vaswani Path, Near G.P.O, Near Pune Railway Station\nTimings: 11:00 AM - 7:00 PM\nEntry fees: 0\nThe museum is near Pune railway station, so you can easily take a taxi/cab or bus till the museum\n\n"+
                "tribal cultural museum\nTribal Research & Training Institute, Pune 28, Queen’s Garden, Pune\nTimings:10:30 AM - 5:30 PM\nEntry fees: INR 10 for Indians; INR 200 for foreigners\nLocated on Queen's road, you can reach here by taking a cab or bus.\n\n"+
                "Aga Khan Palace And Gandhi National Memorial\nPune Nagar Road, Kalyani Nagar, Pune\n9:00 AM - 5:30 PM\nEntry fees: INR 5 for Indians; INR 2 for children; INR 100 for foreigners\nLocated at Nagar Road, you can reach here by taking an auto, cab or state buses.\n\n"+
                "Rajgad Fort\nRajgad Fort, Rajgad, Pune\nTimings:10:00 AM - 6:00 PM\nEntry fees: 0\nLocated in Rajgad, this fort can be reached by cabs or taxis\n\n");
    }//GEN-LAST:event_tourist_histActionPerformed

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ent_beaches;
    private javax.swing.JButton ent_malls;
    private javax.swing.JTextArea entertainment;
    private javax.swing.JButton exit;
    private javax.swing.JButton hosp_govt;
    private javax.swing.JButton hosp_private;
    private javax.swing.JTextArea hospitals;
    private javax.swing.JTextArea hotels;
    private javax.swing.JButton hotels_3star;
    private javax.swing.JButton hotels_4star;
    private javax.swing.JButton hotels_5star;
    private javax.swing.JButton hotels_others;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea tourist_attraction;
    private javax.swing.JButton tourist_hist;
    private javax.swing.JButton tourist_relig;
    private javax.swing.JButton trans_air;
    private javax.swing.JButton trans_rail;
    private javax.swing.JButton trans_road;
    private javax.swing.JTextArea transport;
    // End of variables declaration//GEN-END:variables
}
